### ISSUE TITLE
Unify to a Single Python File

### ISSUE THREAD

**Issue by engineerjoe440** [engineerjoe440/pycev#15]
Why are we nesting a single file in a single folder? That seems... excessive.

We should just move towards replacing the `pycev/` folder with the single `pycev.py` file.

**Comment by sreekeshiyer** [comment]
Created #17 
I took a look at the imports in the unit test files as well and they should ideally work.

**Comment by engineerjoe440** [comment]
Thank you again, @sreekeshiyer, for your efforts here! This has been completed, and I'm closing this out, now.
